#ifndef __EOS_ANALYTICAL_BAROTROP1D_H__
#define __EOS_ANALYTICAL_BAROTROP1D_H__

#include "CUFLU.h"

#define ANALYTICAL_BAROTROP_AUX_GAMMA       0
#define ANALYTICAL_BAROTROP_AUX_GAMMA_M1    1
#define ANALYTICAL_BAROTROP_AUX__GAMMA_M1   2
#define ANALYTICAL_BAROTROP_AUX_DENS2CGS    3
#define ANALYTICAL_BAROTROP_AUX_M_KB        4
#define ANALYTICAL_BAROTROP_AUX__M_KB       5
#define ANALYTICAL_BAROTROP_AUX_BG_TEMP     6
#define ANALYTICAL_BAROTROP_AUX_N_STAR      7
#endif