#ifndef __EOS_SAUMON_CHABRIER_H__
#define __EOS_SAUMON_CHABRIER_H__

#include "CUFLU.h"

// auxiliary array indices
#define SAUMON_CHABRIER_AUX_NRHO        0
#define SAUMON_CHABRIER_AUX_NENER       1
#define SAUMON_CHABRIER_AUX_NTEMP       2
#define SAUMON_CHABRIER_AUX_NPRES       3

#define SAUMON_CHABRIER_AUX_MAXRHO      0
#define SAUMON_CHABRIER_AUX_MINRHO      1
#define SAUMON_CHABRIER_AUX_MAXENER     2
#define SAUMON_CHABRIER_AUX_MINENER     3
#define SAUMON_CHABRIER_AUX_MAXTEMP     4
#define SAUMON_CHABRIER_AUX_MINTEMP     5
#define SAUMON_CHABRIER_AUX_MAXPRES     6
#define SAUMON_CHABRIER_AUX_MINPRES     7
#define SAUMON_CHABRIER_AUX_DRHO        8
#define SAUMON_CHABRIER_AUX_DENER       9
#define SAUMON_CHABRIER_AUX_DTEMP       10
#define SAUMON_CHABRIER_AUX_DPRES       11
#define SAUMON_CHABRIER_AUX_UNIT_D      12
#define SAUMON_CHABRIER_AUX_UNIT_V      13

// table indices
#define SAUMON_CHABRIER_TAB_LOG_RHO              0
#define SAUMON_CHABRIER_TAB_LOG_ENER             1
#define SAUMON_CHABRIER_TAB_DENSEINT2TEMP        2
#define SAUMON_CHABRIER_TAB_DENSEINT2PRES        3
#define SAUMON_CHABRIER_TAB_DENSEINT2CS          4
#define SAUMON_CHABRIER_TAB_DENSTEMP2EINT        5
#define SAUMON_CHABRIER_TAB_DENSPRES2EINT        6

#endif